import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { useTranslation } from "next-i18next";
import Link from "next/link";
import { Header } from "../components/Header";
import { loadTranslation } from "../util/translations";
import { useState } from "react";

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const translation = await loadTranslation(locale!, ["home"]);

  return {
    props: {
      ...translation,
    },
  };
};

const Home: NextPage = () => {
  const { t } = useTranslation("home");
  const [messagesCounter, setMessagesCounter] = useState(0);

  return (
    <div>
      <Head>
        <title>{t("title")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <h1>{t("title")}</h1>
      <h3>{t("description")}</h3>

      <p>
        {t("unreadMessages", {
          count: messagesCounter,
        })}
      </p>

      <button onClick={() => setMessagesCounter((prev) => prev + 1)}>+</button>
      <button onClick={() => setMessagesCounter((prev) => prev - 1)}>-</button>

      <Link href="/contact">
        <a>{t("contactLink")}</a>
      </Link>
    </div>
  );
};

export default Home;
